import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import axios from "axios";
import styled from "styled-components";

import MemberList from "@/components/list/MemberList";
import CharacterList from "@/components/list/CharacterList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //현재 선택된 Id
  const [selectedName, setSelectedName] = useState<string>("");
  const [selectedIdx, setSelectedIdx] = useState<number>(0);

  const UserData = useQuery({
    queryKey: ["getUserData"],
    queryFn: async () => {
      const data = await axios
        .get("/api/member")
        .then((response) => response.data)
        .catch((error) => {
          console.log(error);
          throw error;
        });
      return data;
    },
    keepPreviousData: true,
    refetchOnWindowFocus: false,
  });

  const setItems = (name: string, idx: number) => {
    setSelectedName(name);
    setSelectedIdx(idx);
    console.log("name, idx", selectedName, selectedIdx);
  };

  return (
    <>
      <Head>
        <title>Game Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage>
        <MemberList data={UserData} clickedFunc={setItems} />
        <h1>현재 선택된 이름 : {selectedName}</h1>

        {selectedName !== "" ? (
          <CharacterList
            UserData={UserData}
            selectedName={selectedName}
            selectedIdx={selectedIdx}
          ></CharacterList>
        ) : (
          <></>
        )}
      </MainPage>
    </>
  );
}

const MainPage = styled.section`
  width: 100%;
`;
