import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import { useQuery } from "react-query";
import axios from "axios";
import styled from "styled-components";

import MemberList from "@/components/list/MemberList";
import CharacterList from "@/components/list/CharacterList";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  //현재 선택된 Id
  const [refresh, setRefresh] = useState<boolean>(false);
  const [selectedName, setSelectedName] = useState<string>("");
  const [selectedIdx, setSelectedIdx] = useState<number>(0);

  const UserData = useQuery({
    queryKey: ["getUserData", refresh],
    queryFn: async () => {
      try {
        const data = await axios
          .create({
            baseURL: process.env.BASE_URL,
          })
          .get("/api/member")
          .then((response) => response.data)
          .catch((error) => {
            console.log(error);
            throw error;
          });
        return data;
      } catch (e) {
        console.log(e);
      }
    },
    keepPreviousData: true,
    refetchOnWindowFocus: false,
  });

  const setItems = (name: string, idx: number) => {
    setSelectedName(name);
    setSelectedIdx(idx);
    console.log("name, idx", selectedName, selectedIdx);
  };

  return (
    <>
      <Head>
        <title>Game Info</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>현재 선택된 이름 : {selectedName}</h1>
      <MainPage>
        <Left>
          <MemberList data={UserData} clickedFunc={setItems} />
          <UpdateButton
            onClick={() => {
              setRefresh(!refresh);
            }}
          >
            새로고침
          </UpdateButton>
        </Left>
        <Right>
          {selectedName !== "" ? (
            <CharacterList
              UserData={UserData}
              selectedName={selectedName}
              selectedIdx={selectedIdx}
            ></CharacterList>
          ) : (
            <></>
          )}
        </Right>
      </MainPage>
    </>
  );
}

const MainPage = styled.section`
  width: 100%;
  display: flex;
  flex-direction: row;
  justify-content: space-between;
  align-items: center;
  gap: 10px;
`;

const Left = styled.div`
  width: 20%;
  height: 100%;
  min-width: 200px;
  /* border-right: 1px solid #cccccc; */
`;

const Right = styled.div`
  width: 100%;
  height: 100%;
`;

const UpdateButton = styled.button`
  width: 100%;
  height: 40px;
  line-height: 40px;
  margin-top: 20px;
  font-size: 18px;
  background-color: #1d94f5;
  color: #ffffff;
  border-radius: 4px;

  cursor: pointer;
`;
